### CREATE
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Evandro duplicado"
}

### READ ALL
GET http://localhost:3000/usuarios

### READ ONE
GET http://localhost:3000/usuarios/20

### UPDATE
POST http://localhost:3000/usuarios/
Content-Type: application/json

{
  "nome": "Evandro duplicado"
}

### Deletar usuário
DELETE http://localhost:3000/usuarios/29