### CREATE
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Leitor duplicado"
}

### READ ALL
GET http://localhost:3000/tasks

### READ ONE
GET http://localhost:3000/tasks/2

### UPDATE
POST http://localhost:3000/tasks/
Content-Type: application/json

{
  "title": "Leitor duplicado"
}

### Deletar usuário
DELETE http://localhost:3000/tasks/29