### CREATE
POST http://localhost:3000/papeis
Content-Type: application/json

{
  "titulo": "Leitor duplicado"
}

### READ ALL
GET http://localhost:3000/papeis

### READ ONE
GET http://localhost:3000/papeis/2

### UPDATE
POST http://localhost:3000/papeis/
Content-Type: application/json

{
  "titulo": "Leitor duplicado"
}

### Deletar usuário
DELETE http://localhost:3000/papeis/29